// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 101000_login.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.login
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"server_id")]
        public int ServerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"ms")]
        public long Ms { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rid")]
        public long Rid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"lv")]
        public int Lv { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"head")]
        public int Head { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int firstNameState { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long serverOpenTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ForceDisconnectResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartbeatReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartbeatResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ms")]
        public long Ms { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReloginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"server_id")]
        public int ServerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_REQ")]
        LoginReq = 101001,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_RESP")]
        LoginResp = 101002,
        [global::ProtoBuf.ProtoEnum(Name = @"FORCE_DISCONNECT_RESP")]
        ForceDisconnectResp = 101004,
        [global::ProtoBuf.ProtoEnum(Name = @"HEARTBEAT_REQ")]
        HeartbeatReq = 101005,
        [global::ProtoBuf.ProtoEnum(Name = @"HEARTBEAT_RESP")]
        HeartbeatResp = 101006,
        [global::ProtoBuf.ProtoEnum(Name = @"RELOGIN_REQ")]
        ReloginReq = 101007,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
