// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 102000_battle.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.battle
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Attr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public long Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Buff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"layers")]
        public int Layers { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long buffValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Skill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Entity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pos")]
        public int Pos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public EntityType Type { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int waveId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attrs")]
        public global::System.Collections.Generic.List<Attr> Attrs { get; } = new global::System.Collections.Generic.List<Attr>();

        [global::ProtoBuf.ProtoMember(7, Name = @"skills")]
        public global::System.Collections.Generic.List<Skill> Skills { get; } = new global::System.Collections.Generic.List<Skill>();

        [global::ProtoBuf.ProtoMember(8, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"degree")]
        public int Degree { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"star")]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"hp")]
        public long Hp { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"mp")]
        public int Mp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Side : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int sideId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int waveId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"entities")]
        public global::System.Collections.Generic.List<Entity> Entities { get; } = new global::System.Collections.Generic.List<Entity>();

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int headId { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int headBox { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"power")]
        public long Power { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Action : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill")]
        public SkillResult Skill
        {
            get { return __pbn__result.Is(2) ? ((SkillResult)__pbn__result.Object) : default; }
            set { __pbn__result = new global::ProtoBuf.DiscriminatedUnion32Object(2, value); }
        }
        public bool ShouldSerializeSkill() => __pbn__result.Is(2);
        public void ResetSkill() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__result, 2);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__result;

        [global::ProtoBuf.ProtoMember(3, Name = @"buff")]
        public BuffResult Buff
        {
            get { return __pbn__result.Is(3) ? ((BuffResult)__pbn__result.Object) : default; }
            set { __pbn__result = new global::ProtoBuf.DiscriminatedUnion32Object(3, value); }
        }
        public bool ShouldSerializeBuff() => __pbn__result.Is(3);
        public void ResetBuff() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__result, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public WaveUpdate WaveUpdate
        {
            get { return __pbn__result.Is(4) ? ((WaveUpdate)__pbn__result.Object) : default; }
            set { __pbn__result = new global::ProtoBuf.DiscriminatedUnion32Object(4, value); }
        }
        public bool ShouldSerializeWaveUpdate() => __pbn__result.Is(4);
        public void ResetWaveUpdate() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__result, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public int roundId
        {
            get { return __pbn__result.Is(5) ? __pbn__result.Int32 : default; }
            set { __pbn__result = new global::ProtoBuf.DiscriminatedUnion32Object(5, value); }
        }
        public bool ShouldSerializeroundId() => __pbn__result.Is(5);
        public void ResetroundId() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__result, 5);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int sourceId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int skillId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int changeMp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int newMp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"effects")]
        public global::System.Collections.Generic.List<SkillEffect> Effects { get; } = new global::System.Collections.Generic.List<SkillEffect>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillEffect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"order")]
        public int Order { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int targetId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool isMiss { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool isCrit { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool isImmunity { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long changeHp { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long newHp { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool isDead { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsPacked = true)]
        public int[] tiggerSkills { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<Attr> updateAttrs { get; } = new global::System.Collections.Generic.List<Attr>();

        [global::ProtoBuf.ProtoMember(12)]
        public global::System.Collections.Generic.List<Buff> addBuffs { get; } = new global::System.Collections.Generic.List<Buff>();

        [global::ProtoBuf.ProtoMember(13)]
        public global::System.Collections.Generic.List<Buff> updateBuffs { get; } = new global::System.Collections.Generic.List<Buff>();

        [global::ProtoBuf.ProtoMember(14, IsPacked = true)]
        public int[] removeBuffIds { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public int changeMp { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public int newMp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int sourceId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"effects")]
        public global::System.Collections.Generic.List<BuffEffect> Effects { get; } = new global::System.Collections.Generic.List<BuffEffect>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<Buff> updateBuffs { get; } = new global::System.Collections.Generic.List<Buff>();

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public int[] removeBuffIds { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<Attr> updateAttrs { get; } = new global::System.Collections.Generic.List<Attr>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffEffect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int sourceId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int buffId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long changeHp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long newHp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool isDead { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaveUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int totalWaveId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Side updateSide { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityStatistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public EntityType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int defId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"harm")]
        public long Harm { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"heal")]
        public long Heal { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long takeHarm { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool isDead { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleStatistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entities")]
        public global::System.Collections.Generic.List<EntityStatistics> Entities { get; } = new global::System.Collections.Generic.List<EntityStatistics>();

        [global::ProtoBuf.ProtoMember(2)]
        public int totalRound { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleTargetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"params", IsPacked = true)]
        public long[] Params { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleTargetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"params", IsPacked = true)]
        public long[] Params { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"defender")]
        public Side Defender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"params", IsPacked = true)]
        public long[] Params { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"skip")]
        public bool Skip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int sceneId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"params", IsPacked = true)]
        public int[] Params { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attcker")]
        public Side Attcker { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"defender")]
        public Side Defender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleRoundReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int waveId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"round")]
        public int Round { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleRoundResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int waveId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"actions")]
        public global::System.Collections.Generic.List<Action> Actions { get; } = new global::System.Collections.Generic.List<Action>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleResultResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result")]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rewards")]
        public global::System.Collections.Generic.List<global::msg.common.IntToLong> Rewards { get; } = new global::System.Collections.Generic.List<global::msg.common.IntToLong>();

        [global::ProtoBuf.ProtoMember(5, Name = @"statistics")]
        public BattleStatistics Statistics { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"extList", IsPacked = true)]
        public long[] extLists { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool isVideo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleSkipReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleEndReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long videoId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attacker")]
        public Side Attacker { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"defender")]
        public Side Defender { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"rounds")]
        public int Rounds { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"statistics")]
        public BattleStatistics Statistics { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"extMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, long> extMaps { get; } = new global::System.Collections.Generic.Dictionary<int, long>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReportListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ReportType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReportListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ReportType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reports")]
        public global::System.Collections.Generic.List<BattleReport> Reports { get; } = new global::System.Collections.Generic.List<BattleReport>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_REQ")]
        BattleReq = 102001,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_RESP")]
        BattleResp = 102002,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_ROUND_REQ")]
        BattleRoundReq = 102003,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_ROUND_RESP")]
        BattleRoundResp = 102004,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_RESULT_RESP")]
        BattleResultResp = 102005,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_SKIP_REQ")]
        BattleSkipReq = 102006,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_REQ")]
        BattleEndReq = 102007,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_REPORT_LIST_REQ")]
        BattleReportListReq = 102008,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_REPORT_LIST_RESP")]
        BattleReportListResp = 102009,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_TARGET_INFO_REQ")]
        BattleTargetInfoReq = 102010,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_TARGET_INFO_RESP")]
        BattleTargetInfoResp = 102011,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EntityType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_TYPE")]
        UnknownType = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO")]
        Hero = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MONSTER")]
        Monster = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReportType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_REPORT_TYPE")]
        UnknownReportType = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA")]
        Arena = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAMPIONSHIP")]
        Championship = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReportExt
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_ARENA_ATK_RANK")]
        ExtArenaAtkRank = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_ARENA_DEF_RANK")]
        ExtArenaDefRank = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_ARENA_ATK_SCORE")]
        ExtArenaAtkScore = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_ARENA_DEF_SCORE")]
        ExtArenaDefScore = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_CHAMPIONSHIP_STAGE")]
        ExtChampionshipStage = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_CHAMPIONSHIP_ROUND")]
        ExtChampionshipRound = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_RECORD_POWER")]
        ExtRecordPower = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"EXT_RECORD_TIME")]
        ExtRecordTime = 7,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
