// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 103000_bag.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.bag
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BagListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"param", IsPacked = true)]
        public int[] Params { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagItemChangeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> decomposeInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagItemUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagCombineBatchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BAG_LIST_REQ")]
        BagListReq = 103001,
        [global::ProtoBuf.ProtoEnum(Name = @"BAG_LIST_RESP")]
        BagListResp = 103002,
        [global::ProtoBuf.ProtoEnum(Name = @"USE_ITEM_REQ")]
        UseItemReq = 103003,
        [global::ProtoBuf.ProtoEnum(Name = @"BAG_ITEM_CHANGE_RESP")]
        BagItemChangeResp = 103004,
        [global::ProtoBuf.ProtoEnum(Name = @"BAG_ITEM_UPDATE_RESP")]
        BagItemUpdateResp = 103005,
        [global::ProtoBuf.ProtoEnum(Name = @"BAG_COMBINE_BATCH_REQ")]
        BagCombineBatchReq = 103006,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
