// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 104000_system.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.system
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TipsCodeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        public int Code { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"params")]
        public global::System.Collections.Generic.List<string> Params { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"command")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Command { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"syntax")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Syntax { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmCommandListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmCommandListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmdList")]
        public global::System.Collections.Generic.List<GmCommand> cmdLists { get; } = new global::System.Collections.Generic.List<GmCommand>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmCommandReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmcommandResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SystemRootReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SystemRootResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"unlock", IsPacked = true)]
        public int[] Unlocks { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool unlockAll { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Setting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SettingListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SettingListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"settings")]
        public global::System.Collections.Generic.List<Setting> Settings { get; } = new global::System.Collections.Generic.List<Setting>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SettingReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"set")]
        public global::System.Collections.Generic.List<Setting> Sets { get; } = new global::System.Collections.Generic.List<Setting>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SettingResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"set")]
        public global::System.Collections.Generic.List<Setting> Sets { get; } = new global::System.Collections.Generic.List<Setting>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"types", IsPacked = true)]
        public global::System.Collections.Generic.List<ReportType> Types { get; } = new global::System.Collections.Generic.List<ReportType>();

        [global::ProtoBuf.ProtoMember(3, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"proves")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Proves { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportProve : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chatType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportProvesReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportProvesResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"proves")]
        public global::System.Collections.Generic.List<ReportProve> Proves { get; } = new global::System.Collections.Generic.List<ReportProve>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TIPS_CODE_RESP")]
        TipsCodeResp = 104001,
        [global::ProtoBuf.ProtoEnum(Name = @"GM_COMMAND_LIST_REQ")]
        GmCommandListReq = 104002,
        [global::ProtoBuf.ProtoEnum(Name = @"GM_COMMAND_LIST_RESP")]
        GmCommandListResp = 104003,
        [global::ProtoBuf.ProtoEnum(Name = @"GM_COMMAND_REQ")]
        GmCommandReq = 104004,
        [global::ProtoBuf.ProtoEnum(Name = @"GMCOMMAND_RESP")]
        GmcommandResp = 104005,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM_ROOT_REQ")]
        SystemRootReq = 104006,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM_ROOT_RESP")]
        SystemRootResp = 104007,
        [global::ProtoBuf.ProtoEnum(Name = @"SETTING_LIST_REQ")]
        SettingListReq = 104010,
        [global::ProtoBuf.ProtoEnum(Name = @"SETTING_LIST_RESP")]
        SettingListResp = 104011,
        [global::ProtoBuf.ProtoEnum(Name = @"SETTING_REQ")]
        SettingReq = 104012,
        [global::ProtoBuf.ProtoEnum(Name = @"SETTING_RESP")]
        SettingResp = 104013,
        [global::ProtoBuf.ProtoEnum(Name = @"REPORT_REQ")]
        ReportReq = 104014,
        [global::ProtoBuf.ProtoEnum(Name = @"REPORT_RESP")]
        ReportResp = 104015,
        [global::ProtoBuf.ProtoEnum(Name = @"REPORT_PROVES_REQ")]
        ReportProvesReq = 104016,
        [global::ProtoBuf.ProtoEnum(Name = @"REPORT_PROVES_RESP")]
        ReportProvesResp = 104017,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReportType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OTHERS_REPORT_TYPE")]
        OthersReportType = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NAME")]
        Name = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ABUSE")]
        Abuse = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ADVERTISE")]
        Advertise = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ABUSE_OR_VIOLENCE")]
        AbuseOrViolence = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"REACTIONARY")]
        Reactionary = 5,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
