// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 105000_pay.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.pay
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PayLimit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int payId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"count")]
        public int Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PayInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PayInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"limits")]
        public global::System.Collections.Generic.List<PayLimit> Limits { get; } = new global::System.Collections.Generic.List<PayLimit>();

        [global::ProtoBuf.ProtoMember(2)]
        public int totalPay { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PayOrderReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int payId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"extList", IsPacked = true)]
        public int[] extLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PayOrderResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string orderId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string userId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string roleName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public int serverId { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serverName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public int payId { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string payName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"amount")]
        public int Amount { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string extInfo { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VoucherPayReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int payId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"extList", IsPacked = true)]
        public int[] extLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DirectPayInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DirectPayInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"firstIdList", IsPacked = true)]
        public int[] firstIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PAY_INFO_REQ")]
        PayInfoReq = 105001,
        [global::ProtoBuf.ProtoEnum(Name = @"PAY_INFO_RESP")]
        PayInfoResp = 105002,
        [global::ProtoBuf.ProtoEnum(Name = @"PAY_ORDER_REQ")]
        PayOrderReq = 105003,
        [global::ProtoBuf.ProtoEnum(Name = @"PAY_ORDER_RESP")]
        PayOrderResp = 105004,
        [global::ProtoBuf.ProtoEnum(Name = @"VOUCHER_PAY_REQ")]
        VoucherPayReq = 105005,
        [global::ProtoBuf.ProtoEnum(Name = @"DIRECT_PAY_INFO_REQ")]
        DirectPayInfoReq = 105006,
        [global::ProtoBuf.ProtoEnum(Name = @"DIRECT_PAY_INFO_RESP")]
        DirectPayInfoResp = 105007,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
