// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 106000_mail.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.mail
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Attachment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"got")]
        public bool Got { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long expireTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Mail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mailId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int configId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"attachment")]
        public global::System.Collections.Generic.List<Attachment> Attachments { get; } = new global::System.Collections.Generic.List<Attachment>();

        [global::ProtoBuf.ProtoMember(6, Name = @"status")]
        public int Status { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long sendTime { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long deleteTime { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mailId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public int Status { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attachment")]
        public global::System.Collections.Generic.List<Attachment> Attachments { get; } = new global::System.Collections.Generic.List<Attachment>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryMailInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryMailInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mails")]
        public global::System.Collections.Generic.List<Mail> Mails { get; } = new global::System.Collections.Generic.List<Mail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewMailsNoticeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mails")]
        public global::System.Collections.Generic.List<Mail> Mails { get; } = new global::System.Collections.Generic.List<Mail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeMailAttachmentReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mailId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeMailAttachmentResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public MailUpdate mailUpdate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeAllMailAttachmentReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeAllMailAttachmentResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mailUpdate")]
        public global::System.Collections.Generic.List<MailUpdate> mailUpdates { get; } = new global::System.Collections.Generic.List<MailUpdate>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mailId", IsPacked = true)]
        public int[] mailIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteMailResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mailId", IsPacked = true)]
        public int[] mailIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mailId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadMailResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public MailUpdate mailUpdate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"QUERY_MAIL_INFO_REQ")]
        QueryMailInfoReq = 106001,
        [global::ProtoBuf.ProtoEnum(Name = @"QUERY_MAIL_INFO_RESP")]
        QueryMailInfoResp = 106002,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_MAILS_NOTICE_RESP")]
        NewMailsNoticeResp = 106003,
        [global::ProtoBuf.ProtoEnum(Name = @"TAKE_MAIL_ATTACHMENT_REQ")]
        TakeMailAttachmentReq = 106004,
        [global::ProtoBuf.ProtoEnum(Name = @"TAKE_MAIL_ATTACHMENT_RESP")]
        TakeMailAttachmentResp = 106005,
        [global::ProtoBuf.ProtoEnum(Name = @"TAKE_ALL_MAIL_ATTACHMENT_REQ")]
        TakeAllMailAttachmentReq = 106006,
        [global::ProtoBuf.ProtoEnum(Name = @"TAKE_ALL_MAIL_ATTACHMENT_RESP")]
        TakeAllMailAttachmentResp = 106007,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE_MAIL_REQ")]
        DeleteMailReq = 106008,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE_MAIL_RESP")]
        DeleteMailResp = 106009,
        [global::ProtoBuf.ProtoEnum(Name = @"READ_MAIL_REQ")]
        ReadMailReq = 106010,
        [global::ProtoBuf.ProtoEnum(Name = @"READ_MAIL_RESP")]
        ReadMailResp = 106011,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
