// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 107000_chat.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.chat
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatChannelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::msg.common.RoleInfo roleInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"num")]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatMessageInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::msg.common.RoleInfo senderInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long sendTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public MsgType msgType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatLoginResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"infos")]
        public global::System.Collections.Generic.List<ChatChannelInfo> Infos { get; } = new global::System.Collections.Generic.List<ChatChannelInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ChatMessageInfo> messageInfos { get; } = new global::System.Collections.Generic.List<ChatMessageInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatReadChannelReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatReadChannelResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatSendMessageReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatSendMessageResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatCloseChannelReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatCloseChannelResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatBroadcastResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ChatMessageInfo messageInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatGetChatRoleReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatGetChatRoleResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public global::msg.common.RoleInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_LOGIN_RESP")]
        ChatLoginResp = 107001,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_GET_INFO_REQ")]
        ChatGetInfoReq = 107002,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_GET_INFO_RESP")]
        ChatGetInfoResp = 107003,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_READ_CHANNEL_REQ")]
        ChatReadChannelReq = 107004,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_READ_CHANNEL_RESP")]
        ChatReadChannelResp = 107005,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_SEND_MESSAGE_REQ")]
        ChatSendMessageReq = 107006,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_SEND_MESSAGE_RESP")]
        ChatSendMessageResp = 107007,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_CLOSE_CHANNEL_REQ")]
        ChatCloseChannelReq = 107008,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_CLOSE_CHANNEL_RESP")]
        ChatCloseChannelResp = 107009,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_BROADCAST_RESP")]
        ChatBroadcastResp = 107010,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_GET_CHAT_ROLE_REQ")]
        ChatGetChatRoleReq = 107011,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT_GET_CHAT_ROLE_RESP")]
        ChatGetChatRoleResp = 107012,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
        Normal = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"UNION_RECRUIT")]
        UnionRecruit = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UNION_INVITE")]
        UnionInvite = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM_MESSAGE")]
        SystemMessage = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
