// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 110000_cross.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.cross
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossAuthorizeReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int serverId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sign")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sign { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"mergeServerId", IsPacked = true)]
        public int[] mergeServerIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossAuthorizeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int serverId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossChatReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel")]
        public int Channel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"info")]
        public global::msg.chat.ChatMessageInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossErrorTipsResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"roleId", IsPacked = true)]
        public long[] roleIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        public int Code { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossRoleInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long requestRoleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossRoleInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long requestRoleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"info")]
        public global::msg.role.RoleInfoResp Info { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        public long Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"friends")]
        public global::System.Collections.Generic.List<global::msg.friend.Friend> Friends { get; } = new global::System.Collections.Generic.List<global::msg.friend.Friend>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendApplyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"codes", IsPacked = true)]
        public int[] Codes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendHandleApplyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"agree")]
        public bool Agree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendHandleApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"codes", IsPacked = true)]
        public int[] Codes { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<global::msg.friend.Friend> newFriends { get; } = new global::System.Collections.Generic.List<global::msg.friend.Friend>();

        [global::ProtoBuf.ProtoMember(4, Name = @"agree")]
        public bool Agree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendNewFriendsResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::msg.friend.Friend> newFriends { get; } = new global::System.Collections.Generic.List<global::msg.friend.Friend>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendDeleteReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendDeleteResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendBlackReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool isAdd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendBlackResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blackList")]
        public global::System.Collections.Generic.List<global::msg.friend.Friend> blackLists { get; } = new global::System.Collections.Generic.List<global::msg.friend.Friend>();

        [global::ProtoBuf.ProtoMember(3)]
        public bool isAdd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendBlackedResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long blackRoleId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool isAdd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendSendDotReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long fromRoleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendLoginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendLoginResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool needUpload { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public long[] friendIds { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public long[] blackIds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"applies")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, long> Applies { get; } = new global::System.Collections.Generic.Dictionary<long, long>();

        [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
        public long[] blackedIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendUploadReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"friend")]
        public global::msg.friend.Friend Friend { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendLogoutReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrossFriendNewApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"apply")]
        public global::msg.friend.Friend Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_AUTHORIZE_REQ")]
        CrossAuthorizeReq = 110001,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_AUTHORIZE_RESP")]
        CrossAuthorizeResp = 110002,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_CHAT_REQ")]
        CrossChatReq = 110003,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_ERROR_TIPS_RESP")]
        CrossErrorTipsResp = 110004,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_ROLE_INFO_REQ")]
        CrossRoleInfoReq = 110005,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_ROLE_INFO_RESP")]
        CrossRoleInfoResp = 110006,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_LIST_REQ")]
        CrossFriendListReq = 110007,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_LIST_RESP")]
        CrossFriendListResp = 110008,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_APPLY_REQ")]
        CrossFriendApplyReq = 110009,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_APPLY_RESP")]
        CrossFriendApplyResp = 110010,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_HANDLE_APPLY_REQ")]
        CrossFriendHandleApplyReq = 110011,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_HANDLE_APPLY_RESP")]
        CrossFriendHandleApplyResp = 110012,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_NEW_APPLY_RESP")]
        CrossFriendNewApplyResp = 110013,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_NEW_FRIENDS_RESP")]
        CrossFriendNewFriendsResp = 110014,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_DELETE_REQ")]
        CrossFriendDeleteReq = 110015,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_DELETE_RESP")]
        CrossFriendDeleteResp = 110016,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_BLACK_REQ")]
        CrossFriendBlackReq = 110017,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_BLACK_RESP")]
        CrossFriendBlackResp = 110018,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_SEND_DOT_REQ")]
        CrossFriendSendDotReq = 110019,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_LOGIN_REQ")]
        CrossFriendLoginReq = 110020,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_LOGIN_RESP")]
        CrossFriendLoginResp = 110021,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_UPLOAD_REQ")]
        CrossFriendUploadReq = 110022,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_LOGOUT_REQ")]
        CrossFriendLogoutReq = 110023,
        [global::ProtoBuf.ProtoEnum(Name = @"CROSS_FRIEND_BLACKED_RESP")]
        CrossFriendBlackedResp = 110029,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
