// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 111000_role.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.role
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int serverId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serverName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"official")]
        public int Official { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long fightPower { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int headId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int headBoxId { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int provinceCode { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int cityCode { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public bool openLocation { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public bool hiddenProgress { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleRenameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleRenameResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleLevelUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int oldLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int newLevel { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] openfunctionIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoUpdateLocationReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool openLocation { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location")]
        public LocationInfo Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LocationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int provinceCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int cityCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoGetLocationReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoGetLocationResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location")]
        public LocationInfo Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfoHiddenProgressReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool hiddenProgress { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RolePowerCompareReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RolePowerCompareResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"left")]
        public PowerCompareInfo Left { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"right")]
        public PowerCompareInfo Right { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PowerCompareInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::msg.common.RoleInfo roleInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"powers")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, long> Powers { get; } = new global::System.Collections.Generic.Dictionary<int, long>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RolePowerCompareDetailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long targetRoleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int modType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RolePowerCompareDetailResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"left")]
        public PowerCompareDetail Left { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"right")]
        public PowerCompareDetail Right { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PowerCompareDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int modType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"hero")]
        public HeroCompareDetail Hero
        {
            get { return __pbn__detail.Is(3) ? ((HeroCompareDetail)__pbn__detail.Object) : default; }
            set { __pbn__detail = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeHero() => __pbn__detail.Is(3);
        public void ResetHero() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__detail, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__detail;

        [global::ProtoBuf.ProtoMember(4, Name = @"equip")]
        public EquipCompareDetail Equip
        {
            get { return __pbn__detail.Is(4) ? ((EquipCompareDetail)__pbn__detail.Object) : default; }
            set { __pbn__detail = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeEquip() => __pbn__detail.Is(4);
        public void ResetEquip() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__detail, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"star")]
        public StarCompareDetail Star
        {
            get { return __pbn__detail.Is(5) ? ((StarCompareDetail)__pbn__detail.Object) : default; }
            set { __pbn__detail = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeStar() => __pbn__detail.Is(5);
        public void ResetStar() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__detail, 5);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroCompareDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int currentShareLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipCompareDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int strengthenLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int qualityLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarCompareDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int starLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int starLevelExp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_REQ")]
        RoleInfoReq = 111001,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_RESP")]
        RoleInfoResp = 111002,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_RENAME_REQ")]
        RoleRenameReq = 111003,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_RENAME_RESP")]
        RoleRenameResp = 111004,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_LEVEL_UP_RESP")]
        RoleLevelUpResp = 111005,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_UPDATE_LOCATION_REQ")]
        RoleInfoUpdateLocationReq = 111006,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_GET_LOCATION_REQ")]
        RoleInfoGetLocationReq = 111007,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_GET_LOCATION_RESP")]
        RoleInfoGetLocationResp = 111008,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_INFO_HIDDEN_PROGRESS_REQ")]
        RoleInfoHiddenProgressReq = 111009,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_POWER_COMPARE_REQ")]
        RolePowerCompareReq = 111010,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_POWER_COMPARE_RESP")]
        RolePowerCompareResp = 111011,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_POWER_COMPARE_DETAIL_REQ")]
        RolePowerCompareDetailReq = 111012,
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_POWER_COMPARE_DETAIL_RESP")]
        RolePowerCompareDetailResp = 111013,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
