// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 112000_hero.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.hero
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"degree")]
        public int Degree { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"star")]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int universeArousalState { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int universeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int lockState { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"talentMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> talentMaps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroCostInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> replaceItems { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public long[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceSlotInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int slotId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long endTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroAddResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<HeroInfo> heroInfos { get; } = new global::System.Collections.Generic.List<HeroInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int autoDismissState { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int resetFreeCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int resetItemCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<HeroInfo> heroInfos { get; } = new global::System.Collections.Generic.List<HeroInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroLevelUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroLevelUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBreakReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBreakResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroChangeLevelReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long sourceUniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long targetUniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroChangeLevelResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInfo sourceHeroInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public HeroInfo targetHeroInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroStarUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"heroCostInfoMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, HeroCostInfo> heroCostInfoMaps { get; } = new global::System.Collections.Generic.Dictionary<int, HeroCostInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroStarUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star")]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"talent")]
        public int Talent { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public long[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSelectTalentReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star")]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"talent")]
        public int Talent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSelectTalentResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star")]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"talent")]
        public int Talent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSetLockReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int lockState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSetLockResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int lockState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSetAutoDismissReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int autoDismissState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroSetAutoDismissResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int autoDismissState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroDismissReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroDismissResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroFreeResetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroFreeResetResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInfo heroInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int resetFreeCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroItemResetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroItemResetResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInfo heroInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int resetItemCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBackReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star")]
        public int Star { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBackResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInfo heroInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIllustratedGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIllustratedGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dataMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> dataMaps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIllustratedGetRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIllustratedGetRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"state")]
        public int State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] mainUniqueIds { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<HeroInheritanceSlotInfo> slotInfos { get; } = new global::System.Collections.Generic.List<HeroInheritanceSlotInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceUnlockSlotReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int slotId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceUnlockSlotResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInheritanceSlotInfo slotInfos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceMoveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int slotId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public int State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceMoveResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public HeroInheritanceSlotInfo slotInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroInheritanceChangeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] mainUniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIncreaseGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIncreaseGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int increaseLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int maxStar { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIncreaseLevelUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroIncreaseLevelUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int increaseLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBrokenGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBrokenGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int brokenLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBrokenLevelUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"heroCostInfoMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, HeroCostInfo> heroCostInfoMaps { get; } = new global::System.Collections.Generic.Dictionary<int, HeroCostInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroBrokenLevelUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int brokenLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public long[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseArousalReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseArousalResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int universeArousalState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseLevelUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseLevelUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int universeLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseResetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroUniverseResetResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int universeArousalState { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int universeLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ADD_RESP")]
        HeroAddResp = 112001,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_GET_INFO_REQ")]
        HeroGetInfoReq = 112002,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_GET_INFO_RESP")]
        HeroGetInfoResp = 112003,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_LEVEL_UP_REQ")]
        HeroLevelUpReq = 112004,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_LEVEL_UP_RESP")]
        HeroLevelUpResp = 112005,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BREAK_REQ")]
        HeroBreakReq = 112006,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BREAK_RESP")]
        HeroBreakResp = 112007,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_CHANGE_LEVEL_REQ")]
        HeroChangeLevelReq = 112008,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_CHANGE_LEVEL_RESP")]
        HeroChangeLevelResp = 112009,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_STAR_UP_REQ")]
        HeroStarUpReq = 112010,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_STAR_UP_RESP")]
        HeroStarUpResp = 112011,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SELECT_TALENT_REQ")]
        HeroSelectTalentReq = 112012,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SELECT_TALENT_RESP")]
        HeroSelectTalentResp = 112013,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SET_LOCK_REQ")]
        HeroSetLockReq = 112014,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SET_LOCK_RESP")]
        HeroSetLockResp = 112015,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SET_AUTO_DISMISS_REQ")]
        HeroSetAutoDismissReq = 112016,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_SET_AUTO_DISMISS_RESP")]
        HeroSetAutoDismissResp = 112017,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_DISMISS_REQ")]
        HeroDismissReq = 112018,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_DISMISS_RESP")]
        HeroDismissResp = 112019,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_FREE_RESET_REQ")]
        HeroFreeResetReq = 112020,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_FREE_RESET_RESP")]
        HeroFreeResetResp = 112021,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ITEM_RESET_REQ")]
        HeroItemResetReq = 112022,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ITEM_RESET_RESP")]
        HeroItemResetResp = 112023,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BACK_REQ")]
        HeroBackReq = 112024,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BACK_RESP")]
        HeroBackResp = 112025,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ILLUSTRATED_GET_INFO_REQ")]
        HeroIllustratedGetInfoReq = 112026,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ILLUSTRATED_GET_INFO_RESP")]
        HeroIllustratedGetInfoResp = 112027,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ILLUSTRATED_GET_REWARD_REQ")]
        HeroIllustratedGetRewardReq = 112028,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_ILLUSTRATED_GET_REWARD_RESP")]
        HeroIllustratedGetRewardResp = 112029,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_GET_INFO_REQ")]
        HeroInheritanceGetInfoReq = 112030,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_GET_INFO_RESP")]
        HeroInheritanceGetInfoResp = 112031,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_UNLOCK_SLOT_REQ")]
        HeroInheritanceUnlockSlotReq = 112032,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_UNLOCK_SLOT_RESP")]
        HeroInheritanceUnlockSlotResp = 112033,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_MOVE_REQ")]
        HeroInheritanceMoveReq = 112034,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_MOVE_RESP")]
        HeroInheritanceMoveResp = 112035,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INHERITANCE_CHANGE_RESP")]
        HeroInheritanceChangeResp = 112036,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INCREASE_GET_INFO_REQ")]
        HeroIncreaseGetInfoReq = 112037,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INCREASE_GET_INFO_RESP")]
        HeroIncreaseGetInfoResp = 112038,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INCREASE_LEVEL_UP_REQ")]
        HeroIncreaseLevelUpReq = 112039,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_INCREASE_LEVEL_UP_RESP")]
        HeroIncreaseLevelUpResp = 112040,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BROKEN_GET_INFO_REQ")]
        HeroBrokenGetInfoReq = 112041,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BROKEN_GET_INFO_RESP")]
        HeroBrokenGetInfoResp = 112042,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BROKEN_LEVEL_UP_REQ")]
        HeroBrokenLevelUpReq = 112043,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_BROKEN_LEVEL_UP_RESP")]
        HeroBrokenLevelUpResp = 112044,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_AROUSAL_REQ")]
        HeroUniverseArousalReq = 112045,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_AROUSAL_RESP")]
        HeroUniverseArousalResp = 112046,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_LEVEL_UP_REQ")]
        HeroUniverseLevelUpReq = 112047,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_LEVEL_UP_RESP")]
        HeroUniverseLevelUpResp = 112048,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_RESET_REQ")]
        HeroUniverseResetReq = 112049,
        [global::ProtoBuf.ProtoEnum(Name = @"HERO_UNIVERSE_RESET_RESP")]
        HeroUniverseResetResp = 112050,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
