// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 113000_store.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.store
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreProductInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int gridId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int productId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int buyCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"reward", IsPacked = true)]
        public int[] Rewards { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"cost", IsPacked = true)]
        public int[] Costs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int freeCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long freeRefreshTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int itemCount { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long itemRefreshTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long storeExpiredTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"productInfo")]
        public global::System.Collections.Generic.List<StoreProductInfo> productInfoes { get; } = new global::System.Collections.Generic.List<StoreProductInfo>();

        [global::ProtoBuf.ProtoMember(8, IsPacked = true)]
        public int[] productIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreLoginInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"storeId", IsPacked = true)]
        public int[] storeIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreSelectReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreSelectResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public StoreInfo storeInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreSelectWishReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"productMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> productMaps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreSelectWishResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] productIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreRefreshReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreRefreshResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public StoreInfo storeInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"multipleKey")]
        public global::System.Collections.Generic.List<global::msg.common.MultipleKey> multipleKeys { get; } = new global::System.Collections.Generic.List<global::msg.common.MultipleKey>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int storeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"productInfo")]
        public global::System.Collections.Generic.List<StoreProductInfo> productInfoes { get; } = new global::System.Collections.Generic.List<StoreProductInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreQuickBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreQuickBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_LOGIN_INFO_RESP")]
        StoreLoginInfoResp = 113001,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_SELECT_REQ")]
        StoreSelectReq = 113002,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_SELECT_RESP")]
        StoreSelectResp = 113003,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_SELECT_WISH_REQ")]
        StoreSelectWishReq = 113004,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_SELECT_WISH_RESP")]
        StoreSelectWishResp = 113005,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_REFRESH_REQ")]
        StoreRefreshReq = 113006,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_REFRESH_RESP")]
        StoreRefreshResp = 113007,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_BUY_REQ")]
        StoreBuyReq = 113008,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_BUY_RESP")]
        StoreBuyResp = 113009,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_QUICK_BUY_REQ")]
        StoreQuickBuyReq = 113010,
        [global::ProtoBuf.ProtoEnum(Name = @"STORE_QUICK_BUY_RESP")]
        StoreQuickBuyResp = 113011,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
