// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 115000_rank.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.rank
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RankRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int headId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int headBox { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"official")]
        public int Official { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"power")]
        public long Power { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rank")]
        public int Rank { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public long Key { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"score")]
        public long Score { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"like")]
        public int Like { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public RankRole roleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProgressInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RankRole roleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool hasReward { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long topStartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long topScore { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public RankRole roleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"likeList")]
        public global::System.Collections.Generic.List<global::msg.common.IntToLong> likeLists { get; } = new global::System.Collections.Generic.List<global::msg.common.IntToLong>();

        [global::ProtoBuf.ProtoMember(2)]
        public bool isRedDot { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] progressIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankBaseListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankBaseListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"baseList")]
        public global::System.Collections.Generic.List<RankBaseInfo> baseLists { get; } = new global::System.Collections.Generic.List<RankBaseInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"list")]
        public global::System.Collections.Generic.List<RankItem> Lists { get; } = new global::System.Collections.Generic.List<RankItem>();

        [global::ProtoBuf.ProtoMember(3, Name = @"self")]
        public RankItem Self { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankLikeReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public long Key { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankLikeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public long Key { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] progressIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] progressIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progressList")]
        public global::System.Collections.Generic.List<ProgressInfo> progressLists { get; } = new global::System.Collections.Generic.List<ProgressInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressDetailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int progressId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankProgressDetailResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int progressId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progressList")]
        public global::System.Collections.Generic.List<ProgressInfo> progressLists { get; } = new global::System.Collections.Generic.List<ProgressInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_INFO_REQ")]
        RankInfoReq = 115001,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_INFO_RESP")]
        RankInfoResp = 115002,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_BASE_LIST_REQ")]
        RankBaseListReq = 115003,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_BASE_LIST_RESP")]
        RankBaseListResp = 115004,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_LIST_REQ")]
        RankListReq = 115005,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_LIST_RESP")]
        RankListResp = 115006,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_LIKE_REQ")]
        RankLikeReq = 115007,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_LIKE_RESP")]
        RankLikeResp = 115008,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_REWARD_REQ")]
        RankProgressRewardReq = 115009,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_REWARD_RESP")]
        RankProgressRewardResp = 115010,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_INFO_REQ")]
        RankProgressInfoReq = 115011,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_INFO_RESP")]
        RankProgressInfoResp = 115012,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_DETAIL_REQ")]
        RankProgressDetailReq = 115013,
        [global::ProtoBuf.ProtoEnum(Name = @"RANK_PROGRESS_DETAIL_RESP")]
        RankProgressDetailResp = 115014,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
