// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 116000_task.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.task
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Task : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group")]
        public int Group { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value")]
        public long Value { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public TaskModudle Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public TaskModudle Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tasks")]
        public global::System.Collections.Generic.List<Task> Tasks { get; } = new global::System.Collections.Generic.List<Task>();

        [global::ProtoBuf.ProtoMember(3)]
        public long refreshTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public TaskModudle Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tasks")]
        public global::System.Collections.Generic.List<Task> Tasks { get; } = new global::System.Collections.Generic.List<Task>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public TaskModudle Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] groupIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK_LIST_REQ")]
        TaskListReq = 116001,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK_LIST_RESP")]
        TaskListResp = 116002,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK_UPDATE_RESP")]
        TaskUpdateResp = 116003,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK_REWARD_REQ")]
        TaskRewardReq = 116004,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TaskModudle
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_MODULE")]
        UnknownModule = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DAILY")]
        Daily = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WEEKLY")]
        Weekly = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CHAMP_GUESS")]
        ChampGuess = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
