// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 117000_on_hook.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.onHook
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int dungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long startTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int freeCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int buyCount { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int compensateCount { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookSpeedUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookSpeedUpResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int freeCount { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int buyCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int compensateCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long onHookTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int beforeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int beforeExp { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int afterLevel { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int afterExp { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> rewardInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookGainRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OnHookGainRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int dungeonId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long startTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long onHookTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int beforeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int beforeExp { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int afterLevel { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int afterExp { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> rewardInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_GET_INFO_REQ")]
        OnHookGetInfoReq = 117001,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_GET_INFO_RESP")]
        OnHookGetInfoResp = 117002,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_SPEED_UP_REQ")]
        OnHookSpeedUpReq = 117003,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_SPEED_UP_RESP")]
        OnHookSpeedUpResp = 117004,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_GAIN_REWARD_REQ")]
        OnHookGainRewardReq = 117005,
        [global::ProtoBuf.ProtoEnum(Name = @"ON_HOOK_GAIN_REWARD_RESP")]
        OnHookGainRewardResp = 117006,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
