// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 118000_func.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.func
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncLoginInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] openfunctionIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] gotfunctionIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncOpenResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"functionId", IsPacked = true)]
        public int[] functionIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] openfunctionIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] gotfunctionIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncGainRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int functionId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncGainRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"functionId", IsPacked = true)]
        public int[] functionIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncManualInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncManualInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int functionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Tasks { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncManualInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public global::System.Collections.Generic.List<FuncManualInfo> Infoes { get; } = new global::System.Collections.Generic.List<FuncManualInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncManualUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public global::System.Collections.Generic.List<FuncManualInfo> Infoes { get; } = new global::System.Collections.Generic.List<FuncManualInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FuncManualRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int functionId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_LOGIN_INFO_RESP")]
        FuncLoginInfoResp = 118001,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_OPEN_RESP")]
        FuncOpenResp = 118002,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_GET_INFO_REQ")]
        FuncGetInfoReq = 118003,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_GET_INFO_RESP")]
        FuncGetInfoResp = 118004,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_GAIN_REWARD_REQ")]
        FuncGainRewardReq = 118005,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_GAIN_REWARD_RESP")]
        FuncGainRewardResp = 118006,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_MANUAL_INFO_REQ")]
        FuncManualInfoReq = 118007,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_MANUAL_INFO_RESP")]
        FuncManualInfoResp = 118008,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_MANUAL_UPDATE_RESP")]
        FuncManualUpdateResp = 118009,
        [global::ProtoBuf.ProtoEnum(Name = @"FUNC_MANUAL_REWARD_REQ")]
        FuncManualRewardReq = 118010,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
