// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 119000_arena.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.arena
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int freeTimes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"topList")]
        public global::System.Collections.Generic.List<global::msg.rank.RankItem> topLists { get; } = new global::System.Collections.Generic.List<global::msg.rank.RankItem>();

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] timesRewards { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"score")]
        public long Score { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"rank")]
        public int Rank { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool canSkip { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long seasonTime { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int seasonFightTimes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaMatchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaMatchResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"matchList")]
        public global::System.Collections.Generic.List<global::msg.rank.RankItem> matchLists { get; } = new global::System.Collections.Generic.List<global::msg.rank.RankItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaRefreshReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaRefreshResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"matchList")]
        public global::System.Collections.Generic.List<global::msg.rank.RankItem> matchLists { get; } = new global::System.Collections.Generic.List<global::msg.rank.RankItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaTimesRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaTimesRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArenaNewSeasonResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long oldScore { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int oldRank { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long newScore { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_INFO_REQ")]
        ArenaInfoReq = 119001,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_INFO_RESP")]
        ArenaInfoResp = 119002,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_MATCH_REQ")]
        ArenaMatchReq = 119003,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_MATCH_RESP")]
        ArenaMatchResp = 119004,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_REFRESH_REQ")]
        ArenaRefreshReq = 119005,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_REFRESH_RESP")]
        ArenaRefreshResp = 119006,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_NEW_SEASON_RESP")]
        ArenaNewSeasonResp = 119007,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_TIMES_REWARD_REQ")]
        ArenaTimesRewardReq = 119008,
        [global::ProtoBuf.ProtoEnum(Name = @"ARENA_TIMES_REWARD_RESP")]
        ArenaTimesRewardResp = 119009,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
