// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 120000_vip.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.vip
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VipInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dailyRewardsLevel", IsPacked = true)]
        public int[] dailyRewardsLevels { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"vipGiftLevel", IsPacked = true)]
        public int[] vipGiftLevels { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"luxuryGiftLevel", IsPacked = true)]
        public int[] luxuryGiftLevels { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"exclusiveGiftLevel", IsPacked = true)]
        public int[] exclusiveGiftLevels { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipGiftBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipGiftBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LuxuryGiftBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LuxuryGiftBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyReceiveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyReceiveResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipExclusiveGiftBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"exclusiveGiftLevel", IsPacked = true)]
        public int[] exclusiveGiftLevels { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"VIP_INFO_REQ")]
        VipInfoReq = 120001,
        [global::ProtoBuf.ProtoEnum(Name = @"VIP_INFO_RESP")]
        VipInfoResp = 120002,
        [global::ProtoBuf.ProtoEnum(Name = @"VIP_GIFT_BUY_REQ")]
        VipGiftBuyReq = 120003,
        [global::ProtoBuf.ProtoEnum(Name = @"VIP_GIFT_BUY_RESP")]
        VipGiftBuyResp = 120004,
        [global::ProtoBuf.ProtoEnum(Name = @"LUXURY_GIFT_BUY_REQ")]
        LuxuryGiftBuyReq = 120005,
        [global::ProtoBuf.ProtoEnum(Name = @"LUXURY_GIFT_BUY_RESP")]
        LuxuryGiftBuyResp = 120006,
        [global::ProtoBuf.ProtoEnum(Name = @"DAILY_RECEIVE_REQ")]
        DailyReceiveReq = 120007,
        [global::ProtoBuf.ProtoEnum(Name = @"DAILY_RECEIVE_RESP")]
        DailyReceiveResp = 120008,
        [global::ProtoBuf.ProtoEnum(Name = @"VIP_EXCLUSIVE_GIFT_BUY_RESP")]
        VipExclusiveGiftBuyResp = 120009,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
