// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 122000_friend.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.friend
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Friend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::msg.common.RoleInfo roleInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool hasFriendDot { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool sentFriendDot { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool isCross { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"friends")]
        public global::System.Collections.Generic.List<Friend> Friends { get; } = new global::System.Collections.Generic.List<Friend>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewFriendResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Friend> newFriends { get; } = new global::System.Collections.Generic.List<Friend>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApplyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"apply")]
        public Friend Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HandleApplyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"agree")]
        public bool Agree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HandleApplyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"agree")]
        public bool Agree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlackReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool isAdd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlackResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blackList")]
        public global::System.Collections.Generic.List<Friend> blackLists { get; } = new global::System.Collections.Generic.List<Friend>();

        [global::ProtoBuf.ProtoMember(2)]
        public bool isAdd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecommendListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecommendListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"recommendList")]
        public global::System.Collections.Generic.List<Friend> recommendLists { get; } = new global::System.Collections.Generic.List<Friend>();

        [global::ProtoBuf.ProtoMember(2, Name = @"appliedList", IsPacked = true)]
        public long[] appliedLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"searchList")]
        public global::System.Collections.Generic.List<Friend> searchLists { get; } = new global::System.Collections.Generic.List<Friend>();

        [global::ProtoBuf.ProtoMember(2, Name = @"appliedList", IsPacked = true)]
        public long[] appliedLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendDotReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendDotResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int sendDotCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReceiveDotReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReceiveDotResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ridList", IsPacked = true)]
        public long[] ridLists { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int receiveDotCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendDataReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendDataResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int receiveDotCount { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int sendDotCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int friendCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int crossFriendCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewDotResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long friendId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FRIEND_LIST_REQ")]
        FriendListReq = 122001,
        [global::ProtoBuf.ProtoEnum(Name = @"FRIEND_LIST_RESP")]
        FriendListResp = 122002,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_FRIEND_RESP")]
        NewFriendResp = 122003,
        [global::ProtoBuf.ProtoEnum(Name = @"APPLY_REQ")]
        ApplyReq = 122004,
        [global::ProtoBuf.ProtoEnum(Name = @"APPLY_RESP")]
        ApplyResp = 122005,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_APPLY_RESP")]
        NewApplyResp = 122006,
        [global::ProtoBuf.ProtoEnum(Name = @"HANDLE_APPLY_REQ")]
        HandleApplyReq = 122007,
        [global::ProtoBuf.ProtoEnum(Name = @"HANDLE_APPLY_RESP")]
        HandleApplyResp = 122008,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE_REQ")]
        DeleteReq = 122009,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE_RESP")]
        DeleteResp = 122010,
        [global::ProtoBuf.ProtoEnum(Name = @"BLACK_REQ")]
        BlackReq = 122011,
        [global::ProtoBuf.ProtoEnum(Name = @"BLACK_RESP")]
        BlackResp = 122012,
        [global::ProtoBuf.ProtoEnum(Name = @"RECOMMEND_LIST_REQ")]
        RecommendListReq = 122013,
        [global::ProtoBuf.ProtoEnum(Name = @"RECOMMEND_LIST_RESP")]
        RecommendListResp = 122014,
        [global::ProtoBuf.ProtoEnum(Name = @"SEARCH_REQ")]
        SearchReq = 122015,
        [global::ProtoBuf.ProtoEnum(Name = @"SEARCH_RESP")]
        SearchResp = 122016,
        [global::ProtoBuf.ProtoEnum(Name = @"SEND_DOT_REQ")]
        SendDotReq = 122017,
        [global::ProtoBuf.ProtoEnum(Name = @"SEND_DOT_RESP")]
        SendDotResp = 122018,
        [global::ProtoBuf.ProtoEnum(Name = @"RECEIVE_DOT_REQ")]
        ReceiveDotReq = 122019,
        [global::ProtoBuf.ProtoEnum(Name = @"RECEIVE_DOT_RESP")]
        ReceiveDotResp = 122020,
        [global::ProtoBuf.ProtoEnum(Name = @"FRIEND_DATA_REQ")]
        FriendDataReq = 122021,
        [global::ProtoBuf.ProtoEnum(Name = @"FRIEND_DATA_RESP")]
        FriendDataResp = 122022,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_DOT_RESP")]
        NewDotResp = 122023,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
