// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 123000_trial.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.trial
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typeLevel")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> typeLevels { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(2, Name = @"degreeReward")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> degreeRewards { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(3, Name = @"freeSweepCnt")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> freeSweepCnts { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(4, Name = @"paySweepCnt")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> paySweepCnts { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(5, Name = @"canPaySweepCnt")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> canPaySweepCnts { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialReceiveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialReceiveResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialSweepReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialSweepResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialSweepBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialSweepBuyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialLevelStrategyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StrategyUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"vid")]
        public long Vid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long fightPower { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int headId { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int headBoxId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialLevelStrategyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"userInfo")]
        public global::System.Collections.Generic.List<StrategyUserInfo> userInfoes { get; } = new global::System.Collections.Generic.List<StrategyUserInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_GET_INFO_REQ")]
        TrialGetInfoReq = 123001,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_GET_INFO_RESP")]
        TrialGetInfoResp = 123002,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_RECEIVE_REQ")]
        TrialReceiveReq = 123003,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_RECEIVE_RESP")]
        TrialReceiveResp = 123004,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_SWEEP_REQ")]
        TrialSweepReq = 123005,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_SWEEP_RESP")]
        TrialSweepResp = 123006,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_SWEEP_BUY_REQ")]
        TrialSweepBuyReq = 123007,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_SWEEP_BUY_RESP")]
        TrialSweepBuyResp = 123008,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_LEVEL_STRATEGY_REQ")]
        TrialLevelStrategyReq = 123009,
        [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_LEVEL_STRATEGY_RESP")]
        TrialLevelStrategyResp = 123010,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
