// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 124000_fight_daily.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.fightdaily
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FightDaily : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int passedInedx { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rewardedProgressList", IsPacked = true)]
        public int[] rewardedProgressLists { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int freeSweepTimes { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int buySweepTimes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FightDailyInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FightDailyInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"infoList")]
        public global::System.Collections.Generic.List<FightDaily> infoLists { get; } = new global::System.Collections.Generic.List<FightDaily>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FightDailySweepReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"times")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Times { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(2)]
        public bool isFree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FightDailySweepResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"times")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Times { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(2)]
        public bool isFree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FIGHT_DAILY_INFO_REQ")]
        FightDailyInfoReq = 124000,
        [global::ProtoBuf.ProtoEnum(Name = @"FIGHT_DAILY_INFO_RESP")]
        FightDailyInfoResp = 124001,
        [global::ProtoBuf.ProtoEnum(Name = @"FIGHT_DAILY_SWEEP_REQ")]
        FightDailySweepReq = 124002,
        [global::ProtoBuf.ProtoEnum(Name = @"FIGHT_DAILY_SWEEP_RESP")]
        FightDailySweepResp = 124003,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
