// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 126000_travel.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.travel
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int travelLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"levelTask")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> levelTasks { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(3)]
        public bool autoState { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"autoQuality", IsPacked = true)]
        public int[] autoQualities { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"task")]
        public global::System.Collections.Generic.List<TravelTask> Tasks { get; } = new global::System.Collections.Generic.List<TravelTask>();

        [global::ProtoBuf.ProtoMember(6)]
        public int freeCnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int taskId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int nameIndex { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long endTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"heroUniqueId", IsPacked = true)]
        public long[] heroUniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelRefreshReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelRefreshResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"task")]
        public global::System.Collections.Generic.List<TravelTask> Tasks { get; } = new global::System.Collections.Generic.List<TravelTask>();

        [global::ProtoBuf.ProtoMember(2)]
        public int freeCnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelDispatchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"heroUniqueId", IsPacked = true)]
        public long[] heroUniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelDispatchResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"task")]
        public TravelTask Task { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelSpeedReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelSpeedResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelReceiveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int uniqueId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelReceiveResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uniqueId", IsPacked = true)]
        public int[] uniqueIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelAutoAcceptReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool autoState { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"autoQuality", IsPacked = true)]
        public int[] autoQualities { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelLevelTaskUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int travelLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"levelTask")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> levelTasks { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_GET_INFO_REQ")]
        TravelGetInfoReq = 126001,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_GET_INFO_RESP")]
        TravelGetInfoResp = 126002,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_REFRESH_REQ")]
        TravelRefreshReq = 126003,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_REFRESH_RESP")]
        TravelRefreshResp = 126004,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_DISPATCH_REQ")]
        TravelDispatchReq = 126005,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_DISPATCH_RESP")]
        TravelDispatchResp = 126006,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_SPEED_REQ")]
        TravelSpeedReq = 126007,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_SPEED_RESP")]
        TravelSpeedResp = 126008,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_RECEIVE_REQ")]
        TravelReceiveReq = 126009,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_RECEIVE_RESP")]
        TravelReceiveResp = 126010,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_AUTO_ACCEPT_REQ")]
        TravelAutoAcceptReq = 126011,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAVEL_LEVEL_TASK_UPDATE_RESP")]
        TravelLevelTaskUpdateResp = 126012,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
