// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 129000_red_dot.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.redDot
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RedDotGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RedDotGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"keys")]
        public global::System.Collections.Generic.List<global::msg.common.MultipleKey> Keys { get; } = new global::System.Collections.Generic.List<global::msg.common.MultipleKey>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RedDotUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"keys")]
        public global::System.Collections.Generic.List<global::msg.common.MultipleKey> Keys { get; } = new global::System.Collections.Generic.List<global::msg.common.MultipleKey>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RED_DOT_GET_INFO_REQ")]
        RedDotGetInfoReq = 129001,
        [global::ProtoBuf.ProtoEnum(Name = @"RED_DOT_GET_INFO_RESP")]
        RedDotGetInfoResp = 129002,
        [global::ProtoBuf.ProtoEnum(Name = @"RED_DOT_UPDATE_RESP")]
        RedDotUpdateResp = 129003,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
