// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 131000_experience.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.experience
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ExperienceGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExperienceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Data { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExperienceGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public global::System.Collections.Generic.List<ExperienceInfo> Infoes { get; } = new global::System.Collections.Generic.List<ExperienceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPERIENCE_GET_INFO_REQ")]
        ExperienceGetInfoReq = 131001,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPERIENCE_GET_INFO_RESP")]
        ExperienceGetInfoResp = 131002,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
