// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 132000_starmap.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.starmap
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"openStarMapId", IsPacked = true)]
        public int[] openStarMapIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, StarMapTaskInfo> Tasks { get; } = new global::System.Collections.Generic.Dictionary<int, StarMapTaskInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public int Value { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public StarMapInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapTaskUpdateResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public StarMapInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapTaskReceiveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int taskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarMapOpenReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int starMapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STAR_MAP_GET_INFO_REQ")]
        StarMapGetInfoReq = 132001,
        [global::ProtoBuf.ProtoEnum(Name = @"STAR_MAP_GET_INFO_RESP")]
        StarMapGetInfoResp = 132002,
        [global::ProtoBuf.ProtoEnum(Name = @"STAR_MAP_TASK_UPDATE_RESP")]
        StarMapTaskUpdateResp = 132003,
        [global::ProtoBuf.ProtoEnum(Name = @"STAR_MAP_TASK_RECEIVE_REQ")]
        StarMapTaskReceiveReq = 132004,
        [global::ProtoBuf.ProtoEnum(Name = @"STAR_MAP_OPEN_REQ")]
        StarMapOpenReq = 132005,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
