// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 133000_like.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.like
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"exp")]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"itemMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> itemMaps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] levelIds { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
        public int[] storyIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int likeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int likeExp { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<LikeInfo> likeInfos { get; } = new global::System.Collections.Generic.List<LikeInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGiveItemReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"itemMap")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> itemMaps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGiveItemResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int heroLevel { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int heroExp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int likeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int likeExp { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<global::msg.common.ResourceInfo> resourceInfos { get; } = new global::System.Collections.Generic.List<global::msg.common.ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeHeroLevelChangeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int beforeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int afterLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeLevelChangeResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int beforeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int afterLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGainHeroRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGainHeroRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGainStoryRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int storyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeGainStoryRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int heroId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int storyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GET_INFO_REQ")]
        LikeGetInfoReq = 133001,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GET_INFO_RESP")]
        LikeGetInfoResp = 133002,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GIVE_ITEM_REQ")]
        LikeGiveItemReq = 133003,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GIVE_ITEM_RESP")]
        LikeGiveItemResp = 133004,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_HERO_LEVEL_CHANGE_RESP")]
        LikeHeroLevelChangeResp = 133005,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_LEVEL_CHANGE_RESP")]
        LikeLevelChangeResp = 133006,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GAIN_HERO_REWARD_REQ")]
        LikeGainHeroRewardReq = 133007,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GAIN_HERO_REWARD_RESP")]
        LikeGainHeroRewardResp = 133008,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GAIN_STORY_REWARD_REQ")]
        LikeGainStoryRewardReq = 133009,
        [global::ProtoBuf.ProtoEnum(Name = @"LIKE_GAIN_STORY_REWARD_RESP")]
        LikeGainStoryRewardResp = 133010,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
