// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 134000_championship.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.championship
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TabInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tab")]
        public int Tab { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long startTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long endTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"state")]
        public int State { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TabInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TabInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tabList")]
        public global::System.Collections.Generic.List<TabInfo> tabLists { get; } = new global::System.Collections.Generic.List<TabInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RestInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RestInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long nextOpenTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"topList")]
        public global::System.Collections.Generic.List<global::msg.rank.RankItem> topLists { get; } = new global::System.Collections.Generic.List<global::msg.rank.RankItem>();

        [global::ProtoBuf.ProtoMember(3)]
        public int lastRank { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int historyRank { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int arenaRank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrepareInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrepareInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long nextOpenTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int lastRank { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int historyRank { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int arenaRank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MyMatchInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MyMatchInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"joined")]
        public bool Joined { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int arenaRank { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long prepareEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long guessEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long battleEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int matchId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"attacker")]
        public global::msg.battle.Side Attacker { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"defender")]
        public global::msg.battle.Side Defender { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VideoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int matchId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long prepareEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long guessEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long battleEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int matchId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attacker")]
        public global::msg.battle.Side Attacker { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"defender")]
        public global::msg.battle.Side Defender { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int attackerSupport { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int defenderSupport { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int matchId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int roleId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int coinNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int matchId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int attackerSupport { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int defenderSupport { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Guess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attcker")]
        public global::msg.common.RoleInfo Attcker { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"defender")]
        public global::msg.common.RoleInfo Defender { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long winnerId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stage")]
        public Stage Stage { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int coinNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessListResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"guessList")]
        public global::System.Collections.Generic.List<Guess> guessLists { get; } = new global::System.Collections.Generic.List<Guess>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessLevelInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessLevelInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] rewardedLevels { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessLevelRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessLevelRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Match : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int matchId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long attackerId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long defenderId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long winnerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public GroupType groupType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public GroupType groupType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"roles")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, global::msg.common.RoleInfo> Roles { get; } = new global::System.Collections.Generic.Dictionary<int, global::msg.common.RoleInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"matchList")]
        public global::System.Collections.Generic.List<Match> matchLists { get; } = new global::System.Collections.Generic.List<Match>();

        [global::ProtoBuf.ProtoMember(4)]
        public long roundEndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InvitationResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int arenaRank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GuessNotifyResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage")]
        public Stage Stage { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"round")]
        public int Round { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attacker")]
        public global::msg.common.RoleInfo Attacker { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"defender")]
        public global::msg.common.RoleInfo Defender { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long expireTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IgnoreGuessNotifyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TopRolesResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"roles")]
        public global::System.Collections.Generic.List<global::msg.common.RoleInfo> Roles { get; } = new global::System.Collections.Generic.List<global::msg.common.RoleInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TAB_INFO_REQ")]
        TabInfoReq = 134001,
        [global::ProtoBuf.ProtoEnum(Name = @"TAB_INFO_RESP")]
        TabInfoResp = 134002,
        [global::ProtoBuf.ProtoEnum(Name = @"REST_INFO_REQ")]
        RestInfoReq = 134003,
        [global::ProtoBuf.ProtoEnum(Name = @"REST_INFO_RESP")]
        RestInfoResp = 134004,
        [global::ProtoBuf.ProtoEnum(Name = @"PREPARE_INFO_REQ")]
        PrepareInfoReq = 134005,
        [global::ProtoBuf.ProtoEnum(Name = @"PREPARE_INFO_RESP")]
        PrepareInfoResp = 134006,
        [global::ProtoBuf.ProtoEnum(Name = @"MY_MATCH_INFO_REQ")]
        MyMatchInfoReq = 134007,
        [global::ProtoBuf.ProtoEnum(Name = @"MY_MATCH_INFO_RESP")]
        MyMatchInfoResp = 134008,
        [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_REQ")]
        VideoReq = 134009,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_INFO_REQ")]
        GuessInfoReq = 134010,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_INFO_RESP")]
        GuessInfoResp = 134011,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_REQ")]
        GuessReq = 134012,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_RESP")]
        GuessResp = 134013,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LIST_REQ")]
        GuessListReq = 134014,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LIST_RESP")]
        GuessListResp = 134015,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LEVEL_INFO_REQ")]
        GuessLevelInfoReq = 134016,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LEVEL_INFO_RESP")]
        GuessLevelInfoResp = 134017,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LEVEL_REWARD_REQ")]
        GuessLevelRewardReq = 134018,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_LEVEL_REWARD_RESP")]
        GuessLevelRewardResp = 134019,
        [global::ProtoBuf.ProtoEnum(Name = @"MATCH_INFO_REQ")]
        MatchInfoReq = 134020,
        [global::ProtoBuf.ProtoEnum(Name = @"MATCH_INFO_RESP")]
        MatchInfoResp = 134021,
        [global::ProtoBuf.ProtoEnum(Name = @"INVITATION_RESP")]
        InvitationResp = 134022,
        [global::ProtoBuf.ProtoEnum(Name = @"GUESS_NOTIFY_RESP")]
        GuessNotifyResp = 134023,
        [global::ProtoBuf.ProtoEnum(Name = @"IGNORE_GUESS_NOTIFY_REQ")]
        IgnoreGuessNotifyReq = 134024,
        [global::ProtoBuf.ProtoEnum(Name = @"TOP_ROLES_RESP")]
        TopRolesResp = 134025,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Stage
    {
        [global::ProtoBuf.ProtoEnum(Name = @"REST")]
        Rest = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PREPARE")]
        Prepare = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SELECT")]
        Select = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"KNOCKOUT")]
        Knockout = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CALC")]
        Calc = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum GroupType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_FINAL")]
        GroupFinal = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_A")]
        GroupA = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_B")]
        GroupB = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_C")]
        GroupC = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_D")]
        GroupD = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
