// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 135000_abstraction.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.abstraction
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int gridId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int costItemId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int costItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long startTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionGetInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionGetInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int abstractionNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<AbstractionInfo> abstractionInfos { get; } = new global::System.Collections.Generic.List<AbstractionInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionDoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int costItemId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int costItemNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionDoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AbstractionInfo abstractionInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionGainReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int gridId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AbstractionGainResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AbstractionInfo abstractionInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_GET_INFO_REQ")]
        AbstractionGetInfoReq = 135001,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_GET_INFO_RESP")]
        AbstractionGetInfoResp = 135002,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_DO_REQ")]
        AbstractionDoReq = 135003,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_DO_RESP")]
        AbstractionDoResp = 135004,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_GAIN_REQ")]
        AbstractionGainReq = 135005,
        [global::ProtoBuf.ProtoEnum(Name = @"ABSTRACTION_GAIN_RESP")]
        AbstractionGainResp = 135006,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
