// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: 136000_holy_land.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.holyland
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandLevel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int levelId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star")]
        public int Star { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandChapter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"levels")]
        public global::System.Collections.Generic.List<HolyLandLevel> Levels { get; } = new global::System.Collections.Generic.List<HolyLandLevel>();

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] rewardedGears { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandInfoResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chapters")]
        public global::System.Collections.Generic.List<HolyLandChapter> Chapters { get; } = new global::System.Collections.Generic.List<HolyLandChapter>();

        [global::ProtoBuf.ProtoMember(2)]
        public int remainSweepTimes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandPassResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public HolyLandLevel Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandSweepReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandSweepResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int remainSweepTimes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gear")]
        public int Gear { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HolyLandRewardResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chapterId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gear")]
        public int Gear { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassRecordReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int levelId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PassRecordResp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int levelId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"fastest")]
        public global::msg.battle.BattleReport Fastest { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::msg.battle.BattleReport minPower { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_INFO_REQ")]
        HolyLandInfoReq = 136001,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_INFO_RESP")]
        HolyLandInfoResp = 136002,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_PASS_RESP")]
        HolyLandPassResp = 136003,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_SWEEP_REQ")]
        HolyLandSweepReq = 136004,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_SWEEP_RESP")]
        HolyLandSweepResp = 136005,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_REWARD_REQ")]
        HolyLandRewardReq = 136006,
        [global::ProtoBuf.ProtoEnum(Name = @"HOLY_LAND_REWARD_RESP")]
        HolyLandRewardResp = 136007,
        [global::ProtoBuf.ProtoEnum(Name = @"PASS_RECORD_REQ")]
        PassRecordReq = 136008,
        [global::ProtoBuf.ProtoEnum(Name = @"PASS_RECORD_RESP")]
        PassRecordResp = 136009,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
