// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: common.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace msg.common
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int uniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"num")]
        public long Num { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"expire")]
        public long Expire { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"tag")]
        public int Tag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultipleKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int subId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IntToLong : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public int Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public long Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultipleResourceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ResourceInfo resourceInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LongToLongArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public long Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsPacked = true)]
        public long[] Values { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IntToResources : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"resourceInfo")]
        public global::System.Collections.Generic.List<ResourceInfo> resourceInfoes { get; } = new global::System.Collections.Generic.List<ResourceInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LongToInt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public long Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public int Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LongToLong : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public long Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public long Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long roleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int serverId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serverName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"official")]
        public int Official { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long fightPower { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long unionId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string unionName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public int unionJob { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int headId { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int headBoxId { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public long offlineTime { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int provinceCode { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public int cityCode { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public int guessLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
